name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Print Directory Contents Before Build
      run: |
        ls -R
        ls -R app

    - name: Build with Maven
      run: |
        cd app
        mvn clean install

    - name: Print Directory Contents After Build
      run: |
        ls -R
        ls -R app/target

    - name: Include target directory
      run: |
        mv app/target .

    - name: Build Docker Image
      run: |
        cd app
        docker build . --file Dockerfile --tag "githubactionsjfrog.jfrog.io/directcicdtojfrog/app:latest"
        docker images

    - name: Test Case Stage
      run: |
        # Add your test cases here
        cd app
        mvn test

    - name: Docker Login to JFrog
      run: echo "${{ secrets.JF_PASSWORD }}" | docker login -u "${{ secrets.JF_USER }}" --password-stdin githubactionsjfrog.jfrog.io

    - name: Docker Push to Jfrog
      run: docker push githubactionsjfrog.jfrog.io/directcicdtojfrog/app:latest

    - name: Build Helm Chart
      run:  |
        wget https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz
        tar -xvzf helm-v3.5.2-linux-amd64.tar.gz
        sudo cp -f linux-amd64/helm /usr/bin
        helm version
        cd app/helmchart  # Change to the Helm chart directory
        ls
        # Adjust the path to values.yaml based on its location within your project structure
        yq e -i '.image.tag = "latest"' values.yaml
        helm template .
        helm lint .
        helm package . --version "1.0.0"

    - name: Upload Helm chart to JFrog Artifactory
      run: |
        cd app
        wget -O jfrog https://getcli.jfrog.io
        chmod +x jfrog
        sudo mv jfrog /usr/local/bin/
        export PATH=$PATH:/usr/local/bin
        jfrog rt c --url https://githubactionsjfrog.jfrog.io/artifactory --interactive=false
        jfrog rt upload --config=./jfrog.yaml "helmchart-1.0.0.tgz" directcicdtojfrog
