name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Print Directory Contents Before Build
      run: |
        ls -R
        ls -R app

    - name: Build with Maven
      run: |
        cd app
        mvn clean install

    - name: Print Directory Contents After Build
      run: |
        ls -R
        ls -R app/target

    - name: Include target directory
      run: |
        mv app/target .
